[feat/EATBOOK-39] 소설 상세 페이지 API 추가
ktb-eatbook/eatbook-app-backend pull request #3
Opened 2024-11-02 09:18 UTC by cjm0611

## 설명

소설 상세 페이지에서 필요한 3가지 API를 구현했습니다.
- **소설 정보 조회 API**: 소설의 ID로 소설의 기본 정보(제목, 저자, 장르 등)를 조회합니다.
- **에피소드 목록 조회 API**: 소설의 에피소드 목록을 페이징하여 반환합니다.
- **가장 최근에 읽은 에피소드 조회 API**: 특정 사용자가 소설에서 마지막으로 읽은 에피소드 정보를 조회합니다.

## 포함된 변경 사항

- 위에서 서술한 API에 대한 컨트롤러, 서비스, 레포지터리, 테스트 코드를 추가했습니다.
- Comment, Favorite, ReadingLog Entity를 추가했습니다.
- QueryDSL을 도입했고, 이를 사용한 쿼리문은 Custom Repository를 생성하여 인터페이스와 구조체로 나눠 구현했습니다.
- checkStyle과 코드 포매터(Goole Style)를 도입하여 코드 스타일이 변경되었습니다.

## 테스트 방법

- 테스트 코드 실행 (MemberServiceTest, NovelServiceTest, ReadingLogServiceTest)

## 추가 참고 사항

- 원래는 3가지 정보(소설 정보, 에피소드 목록, 독서기록)를 하나의 API로 구현하다가 분리한거라 하나의 branch가 되었는데, 변경된 파일 개수가 너무 많네요. 다음부터는 여러 개의 API를 구현할 때 PR을 각각 나눠서 올리겠습니다.

## 리뷰 요청 사항

- 쿼리문이 적절히 작성되었는지(JPA, QueryDSL), 메서드 네이밍이 괜찮은지, 테스트 코드는 적절히 작성되었는지 봐주시면 감사하겠습니다!

2024-11-05 07:20 UTC, pletain requested changes

2024-11-05 07:20 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/member/controller/MemberController.java
> +    public ResponseEntity<?> getMemberBookmarkedNovels(@RequestParam(name = "page") @Min(1) final int page,
유지보수 측면에서 와일드카드 대신 명확한 반환 타입을 지정하는 것이 더 좋을 거 같은데, 추후에 변경하실 생각이 있으신지 여쭤보고 싶습니다.

2024-11-05 07:20 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/member/controller/MemberController.java
>          if (page - 1 > bookmarkedNovels.pagination().totalPages()) {
1. 이 부분은 MemberService에서 처리하면 어떨까 제안드립니다! 구체적으론 Service에서 예외를 던지면 이를 캐치해서 컨트롤러나 전역 예외처리에서 처리하는게 좋을거 같습니다.
Controller는 요청을 받고, Service 계층에서 비즈니스 로직을 처리 후 그 결과를 반환하는 역할을 합니다.
하지만 이 부분은 비즈니스 로직에 가까운 검증 로직이라 생각됩니다. 단순히 입력 값의 형식이나 범위를 확인하는게 아니라, 데이터베이스 조회 결과를 기반으로 한 로직이기 때문입니다. 

2. 이 비교문의 형태가 전체 페이지가 0부터 시작하기 때문에라면,
page - 1 > bookmarkedNovels.pagination().totalPages() 대신 page > bookmarkedNovels.pagination().totalPages() + 1로 수정하는 편이 좀 더 의도가 명확할 거 같아서 제안드려봅니다!

2024-11-05 07:20 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/readingLog/controller/ReadingLogController.java
> +        Map<String, Object> data = new HashMap<>();
명확한 데이터 구조를 위해서 Map 대신 별도의 응답 DTO를 사용하는 것을 제안 드립니다!  타입 안정성과 가독성 측면에서도 더 개선될거 같습니다

2024-11-05 07:20 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/readingLog/service/ReadingLogService.java
> +    @Transactional(readOnly = true)
조회 메서드에 `@Transactional(readOnly = true)`를 설정해서 데이터 일관성 유지하면서 메모리도 절약할 수 있어서 좋은 부분이라고 생각합니다!

2024-11-05 07:20 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/readingLog/service/ReadingLogService.java
> +    public Optional<ContinueReadingInfoDTO> getLastReadEpisode(String memberId, String novelId) {
현재 코드에서 Optional을 사용하고 있는데, 불필요한 Optional 사용은 메모리 오버헤드가 발생할 수 있고, 컨트롤러에서 이를 처리하는 로직이 복잡해질 수 있다고 생각합니다. 예) `lastReadEpisodeOpt.get()`사용으로 인해 추가적인 검사가 필요
따라서 Service 계층에서 Optional 대신 비어 있는 DTO 객체나 null을 반환하여 컨트롤러에서 단순한 null 체크만으로 처리할 수 있도록 변경하는 것이 어떤지 제안드립니다!

[참고자료1](https://velog.io/@hope1213/Optional%EC%9D%80-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EC%A7%80-%EC%82%AC%EC%9A%A9%EC%8B%9C-%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD) [참고자료2](https://dzone.com/articles/using-optional-correctly-is-not-optional) [참고자료3](https://dev-coco.tistory.com/178)

2024-11-05 07:26 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/member/service/MemberService.java
현재 방식은 Bookmark 조회 1번, Favorite 조회 N번(bookmark된 소설 수만큼) 데이터베이스에 호출하는거 같은데,
이 부분을 아래와 같은 하나의 쿼리를 사용해 개선할 수도 있을거 같습니다.
```
    @Query("SELECT b, COUNT(f) AS favoriteCount " +
            "FROM Bookmark b " +
            "LEFT JOIN Favorite f ON f.novel.id = b.novel.id " +
            "WHERE b.member.id = :memberId " +
            "GROUP BY b")
    BookmarkWithFavoriteCountDTO findBookmarksByMemberIdWithFavoriteCount(@Param("memberId") String memberId);
```
하지만 쿼리가 복잡해서, novel_id, member_id 등에 인덱스가 적절히 설정되지 않으면 JOIN, GROUP BY 연산이 느려질 수 있을거 같습니다. 또한 데이터의 양에 따라서 그 결과값도 큰 차이가 있을거 같습니다.
결론적으로 추후에 이 부분은 같이 테스트 및 실험해보면서 리팩토링하면 더 좋을거 같습니다!

2024-11-06 03:13 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/domain/member/controller/MemberController.java
> +    public ResponseEntity<?> getMemberBookmarkedNovels(@RequestParam(name = "page") @Min(1) final int page,
API의 성공, 실패 DTO 타입이 달라서 두 타입을 하나의 타입으로 표현하는 것이 어려워 와일드카드를 사용했습니다. 두 타입을 하나의 타입으로 어떻게 표현하면 될까요? ResponseEntity<Object>로 표현하는 정도로 괜찮을까요?

2024-11-06 03:50 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/member/controller/MemberController.java
> +    public ResponseEntity<?> getMemberBookmarkedNovels(@RequestParam(name = "page") @Min(1) final int page,
ResponseEntity로 표현하는 것도 동일하게 명확한 반환 타입이 없다고 생각됩니다. 저는 아래 두 방식이 떠올라서 제안드려봅니다!

1. 두 DTO가 상속하는 공통 인터페이스나 Wrapper클래스를 만들어서, 이를 반환타입으로 사용
2. 추후에 공통 예외 처리 로직을 도입해서, 컨트롤러에서는 성공 DTO을 반환타입으로 사용하고, 공통 예외처리에선 실패 DTO를 반환타입으로 사용

2024-11-06 04:18 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/domain/member/controller/MemberController.java
> +    public ResponseEntity<?> getMemberBookmarkedNovels(@RequestParam(name = "page") @Min(1) final int page,
이전에 달았던 코멘트에 오타가 났네요. `ResponseEntity<Object>` 정도로 표현해도 괜찮은지 여쭤보려고 했습니다.
제안 주신 방법 중 2번 방법을 MVP 구현 이후에 도입하는 방안으로 진행하겠습니다! 백엔드 노션 문서에 리팩터링 항목으로 적어뒀습니다.

2024-11-06 05:23 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/domain/readingLog/service/ReadingLogService.java
> +    public Optional<ContinueReadingInfoDTO> getLastReadEpisode(String memberId, String novelId) {
Optional을 사용하면 서비스 계층에서 `값이 없을 수 있다`는 의미가 명시적으로 표현할 수 있습니다. Optional을 사용하지 않는다면, 컨트롤러에서 각 DTO나 객체에 대해 null 가능성을 염두에 두고 검사를 해야 합니다. 하지만 Optional 키워드를 일관적으로 사용하면 Optional 키워드가 있는 곳에서만 null 여부를 확인하면 되므로 가독성과 유지보수성에 좋다고 생각합니다.
결국 `메모리 오버헤드를 줄이고 코드의 간결함을 위한 null 사용`과 `Optional을 통해 명시적으로 빈 상태를 표현하여 유지보수성 향상` 사이의 trade-off로 볼 수 있을 것 같은데, 저는 불필요한 Optional 사용은 아니라고 생각합니다!

2024-11-06 05:40 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/domain/member/service/MemberService.java
제안주신 쿼리에 페이지네이션 적용이 안되어 있는 것 같습니다. 페이지네이션 적용하여 변경하면 기존보다 성능이 좋아질 것은 분명해보이는데, 데이터의 양에 따라서 얼마나 성능이 개선될지 차이가 날 것 같아서 말씀주신 것처럼 추후에 리팩터링해보면 좋을 것 같습니다! 이것도 백엔드 문서에 적어뒀습니다.

2024-11-06 07:21 UTC, pletain approved these changes

2024-11-06 07:22 UTC, merged