[feat/EATBOOK-105] 소설 검색하는 API 구현 - 정확도순, 최신순
ktb-eatbook/eatbook-app-backend pull request #7
Opened 2024-11-19 02:12 UTC by cjm0611

## 설명

사용자가 소설을 검색할 때 검색어가 제목이나 작가명에 포함된 소설 목록을 조회하는 API를 구현했습니다.
Levenshtein Distance 알고리즘을 사용하여 검색어가 부분 일치한 경우에 대해서도 정상적으로 유사도가 측정됩니다.
정확도순, 최신순 정렬 기능이 있으며 기본값은 정확도순입니다.

**[정확도순의 판단 기준]**
1순위. `소설 제목`에 검색어가 포함되는가?
2순위. `저자명`에 검색어가 포함되는가?

<br />

**[최신순의 판단 기준]**
1순위. `가장 최근에 릴리즈된 에피소드의 날짜`가 최신인가?
2순위. 소설 간 에피소드 릴리즈 날짜가 동일하다면, 정확도순으로 판단

<br />

## 포함된 변경 사항

- global 패키지의 디렉토리 위치를 domain 패키지와 같은 depth를 가지도록 수정했습니다.
- 소설 검색 시 2개의 쿼리가 발생합니다.
  - 유사도 검색을 위해 소설을 풀스캔으로 가져올 때, fetchJoin을 이용하여 저자, 카테고리, 에피소드 정보를 함께 가져오도록 하여 N+1 문제를 방지했습니다.
  - 페이지네이션 된 소설 리스트의 id 리스트를 기반으로 각 소설의 좋아요 수를 가져옵니다.
- fetchJoin을 위한 소설 Entity의 OneToMany 필드 타입 수정 (ArrayList -> Set)
- queryDSL을 이용한 커스텀 레포지터리 생성
- 기능 구현을 위한 Controller, Service 생성 및 DTO와 Enum 추가

## 테스트 방법

SearchNovelServiceTest에서 아래의 4가지 경우가 정상적으로 동작하는지 테스트를 진행합니다.
- `관련도순 검색 테스트`: 검색어와 관련도가 높은 순으로 소설 목록이 반환되는지 확인
- `최신순 검색 테스트`: 에피소드의 릴리즈 날짜가 최신인 순으로 소설 목록이 반환되는지 확인
- `잘못된 페이지 인덱스 예외 처리`: 유효하지 않은 페이지 인덱스를 요청했을 때 예외가 발생하는지 확인
- `빈 검색 결과 처리`: 검색 결과가 없을 때 빈 결과가 올바르게 처리되는지 확인

## 리뷰 요청 사항

- files changed의 수가 높게 나오는데 global 패키지의 디렉터리 위치 변경때문입니다. 😅 다음부터는 이런 경우 PR을 분리해

2024-11-21 06:56 UTC, pletain requested changes
코드가 전체적으로 잘 작성되어 있어 가독성이 좋았고, 구조적으로도 깔끔해서 좋았습니다! 
몇 가지 사항에 대해 코멘트를 남겼으니 확인 부탁드립니다!

2024-11-21 06:56 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/global/exception/GlobalExceptionHandler.java
>  import org.springframework.validation.BindException;
이전 PR에서 저도 놓친거 같은데, @ExceptionHandler 에서 MethodArgumentTypeMismatchException가 중복되어 있네요!

2024-11-21 06:56 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/global/util/ValidationUtil.java
> +}
validatePageIndex 메서드가 INVALID_QUERY_PARAMETER로 사용하는 방식도 좋지만, 메서드가 페이지 인덱스 검증에 특화된 만큼 INVALID_PAGE_INDEX와 같은 구체적인 에러 메세지를 추가하면 더 명확한 피드백을 제공할 수 있을거 같아 제안드립니다!

다만 운선순위를 고려했을 때, 현재 메시지도 충분히 의도 전달이 된다면 그대로 유지하고 추후에 유사한 메서들이 많아졌을 때 도입을 고려해도 좋을거 같습니다.

2024-11-21 06:56 UTC, pletain commented on src/test/java/com/ktb/eatbookappbackend/search/service/SearchNovelServiceTest.java
> +    }
assertTrue(actualTitles.containsAll())는 순서까지 검증하지 않아서, assertEquals를 사용하는 것이 더 정확할거 같습니다!

`assertEquals(expectedTitles, actualTitles, "전지적 키워드를 포함한 소설들의 우선순위가 정확해야 합니다.");`

2024-11-21 06:56 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/search/service/SearchNovelService.java
> +        }
searchNovelsByRelevance, searchNovelsByLatest로 검색 정렬 로직이 메서드로 분리되어 SRP를 잘 지키고 가독성이 좋은 코드인거 같습니다👍

2024-11-21 06:56 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/search/service/SearchNovelService.java
> +    @Transactional(readOnly = true)
searchNovelsByLatest 메서드는 정렬 로직만 수행하는 것으로 보이는데, @Transactional이 선언되어 있어서 혹시 오탈자인지 여쭤보고 싶습니다!

2024-11-21 06:56 UTC, pletain commented on src/main/java/com/ktb/eatbookappbackend/domain/search/service/SearchNovelService.java
> +    protected SearchNovelsResultDTO createPaginatedResult(List<Novel> sortedNovels, PageRequest pageRequest) {
현재 protected로 선언되어 있는데, 클래스 내부에서만 사용되고 있는거 같아서 private으로 변경하는 것이 어떨지 제안드립니다!

2024-11-21 08:05 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/domain/search/service/SearchNovelService.java
> +    protected SearchNovelsResultDTO createPaginatedResult(List<Novel> sortedNovels, PageRequest pageRequest) {
저도 처음에는 접근 제어자를 private으로 구현했는데 IDE에서 에러를 발생시키더라구요. 찾아보니 `@Transactional`은 AOP 기반으로 동작하는데 private 메서드의 경우 Spring 프록시가제대로 동작하지 않는다고 합니다!
[참고자료](https://velog.io/@ljks789/spring%EC%97%90%EC%84%9C-transactional%EC%97%90-private%EC%9D%B4-%EB%A8%B9%ED%9E%88%EC%A7%80-%EC%95%8A%EB%8A%94-%EC%9D%B4%EC%9C%A0)

2024-11-21 08:29 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/global/exception/GlobalExceptionHandler.java
>  import org.springframework.validation.BindException;
오 매의 눈이시네요! 코드 꼼꼼히 봐주셔서 감사합니다. 다음부터 더 조심하겠습니다!

2024-11-21 08:41 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/global/util/ValidationUtil.java
> +}
page가 쿼리 파라미터로 입력되어서 INVALID_QUERY_PARAMETER를 써도 되지 않을까 생각했는데 분리하는게 명확할 것 같네요!
`유효하지 않은 페이지 번호입니다.`를 반환하도록 수정했습니다.

2024-11-21 09:07 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/domain/search/service/SearchNovelService.java
> +    @Transactional(readOnly = true)
아 불필요한 트랜잭션 어노테이션을 붙였네요! 삭제했습니다!

2024-11-21 09:07 UTC, cjm0611 commented on src/main/java/com/ktb/eatbookappbackend/domain/search/service/SearchNovelService.java
> +    protected SearchNovelsResultDTO createPaginatedResult(List<Novel> sortedNovels, PageRequest pageRequest) {
private으로 변경하고 해당 메서드를 호출하는 상위 메서드에 모두 트랜잭션 어노테이션이 붙어있어 생략했습니다!

2024-11-22 05:45 UTC, pletain approved these changes

2024-11-22 05:46 UTC, merged